#!/bin/bash

# Baseline Simulation Study

OUT_FILE=./baseline/baseline_0_output.dsv
X_POS_INITIAL=49.37
Y_POS_INITIAL=48.71
Z_POS_INITIAL=51.25
X_VEL_INITIAL=5.22
Y_VEL_INITIAL=4.83
Z_VEL_INITIAL=5.13
GRAVITY=9.81
BOX_SIDE_LENGTH=100
GROUP_ID=47bcda
RUN_ID=0
python ball_bounce.py $OUT_FILE $X_POS_INITIAL $Y_POS_INITIAL $Z_POS_INITIAL $X_VEL_INITIAL $Y_VEL_INITIAL $Z_VEL_INITIAL $GRAVITY $BOX_SIDE_LENGTH $GROUP_ID $RUN_ID

OUT_FILE=./baseline/baseline_1_output.dsv
X_POS_INITIAL=50
Y_POS_INITIAL=50
Z_POS_INITIAL=50
X_VEL_INITIAL=5
Y_VEL_INITIAL=5
Z_VEL_INITIAL=5
GRAVITY=9.81
BOX_SIDE_LENGTH=100
GROUP_ID=47bcda
RUN_ID=1
python ball_bounce.py $OUT_FILE $X_POS_INITIAL $Y_POS_INITIAL $Z_POS_INITIAL $X_VEL_INITIAL $Y_VEL_INITIAL $Z_VEL_INITIAL $GRAVITY $BOX_SIDE_LENGTH $GROUP_ID $RUN_ID

OUT_FILE=./baseline/baseline_2_output.dsv
X_POS_INITIAL=51
Y_POS_INITIAL=49
Z_POS_INITIAL=50
X_VEL_INITIAL=5.5
Y_VEL_INITIAL=4.9
Z_VEL_INITIAL=5.1
GRAVITY=9.81
BOX_SIDE_LENGTH=100
GROUP_ID=47bcda
RUN_ID=2
python ball_bounce.py $OUT_FILE $X_POS_INITIAL $Y_POS_INITIAL $Z_POS_INITIAL $X_VEL_INITIAL $Y_VEL_INITIAL $Z_VEL_INITIAL $GRAVITY $BOX_SIDE_LENGTH $GROUP_ID $RUN_ID

OUT_FILE=./baseline/baseline_3_output.dsv
X_POS_INITIAL=49
Y_POS_INITIAL=50
Z_POS_INITIAL=51
X_VEL_INITIAL=5.25
Y_VEL_INITIAL=4.9
Z_VEL_INITIAL=5.0
GRAVITY=9.81
BOX_SIDE_LENGTH=100
GROUP_ID=47bcda
RUN_ID=3
python ball_bounce.py $OUT_FILE $X_POS_INITIAL $Y_POS_INITIAL $Z_POS_INITIAL $X_VEL_INITIAL $Y_VEL_INITIAL $Z_VEL_INITIAL $GRAVITY $BOX_SIDE_LENGTH $GROUP_ID $RUN_ID

python ./dsv_to_sina.py ./baseline ./baseline/baseline_output.sqlite

# Numerical Resolution Study

OUT_FILE=./num_res/num_res_5_output.dsv
X_POS_INITIAL=49
Y_POS_INITIAL=50
Z_POS_INITIAL=51
X_VEL_INITIAL=5.25
Y_VEL_INITIAL=4.9
Z_VEL_INITIAL=5.0
GRAVITY=9.81
BOX_SIDE_LENGTH=100
GROUP_ID=47bcda
RUN_ID=3_5
python ball_bounce_5.py $OUT_FILE $X_POS_INITIAL $Y_POS_INITIAL $Z_POS_INITIAL $X_VEL_INITIAL $Y_VEL_INITIAL $Z_VEL_INITIAL $GRAVITY $BOX_SIDE_LENGTH $GROUP_ID $RUN_ID


OUT_FILE=./num_res/num_res_20_output.dsv
X_POS_INITIAL=49
Y_POS_INITIAL=50
Z_POS_INITIAL=51
X_VEL_INITIAL=5.25
Y_VEL_INITIAL=4.9
Z_VEL_INITIAL=5.0
GRAVITY=9.81
BOX_SIDE_LENGTH=100
GROUP_ID=47bcda
RUN_ID=3_20
python ball_bounce.py $OUT_FILE $X_POS_INITIAL $Y_POS_INITIAL $Z_POS_INITIAL $X_VEL_INITIAL $Y_VEL_INITIAL $Z_VEL_INITIAL $GRAVITY $BOX_SIDE_LENGTH $GROUP_ID $RUN_ID


OUT_FILE=./num_res/num_res_100_output.dsv
X_POS_INITIAL=49
Y_POS_INITIAL=50
Z_POS_INITIAL=51
X_VEL_INITIAL=5.25
Y_VEL_INITIAL=4.9
Z_VEL_INITIAL=5.0
GRAVITY=9.81
BOX_SIDE_LENGTH=100
GROUP_ID=47bcda
RUN_ID=3_100
python ball_bounce_100.py $OUT_FILE $X_POS_INITIAL $Y_POS_INITIAL $Z_POS_INITIAL $X_VEL_INITIAL $Y_VEL_INITIAL $Z_VEL_INITIAL $GRAVITY $BOX_SIDE_LENGTH $GROUP_ID $RUN_ID

python ./dsv_to_sina.py ./num_res ./num_res/num_res_output.sqlite